name: Update Gold Prices

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install packages
        run: |
          pip install requests beautifulsoup4

      - name: Run gold.py
        run: python gold.py
